language: python
python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - make options="-c travis.cfg" version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "#plone.intranet"
